# Config file for automatic testing at travis-ci.org

language: python

# diferrent python versions
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# diferrent django versions
env:
  - DJANGO=django<1.9  # 1.8.x
  - DJANGO=django<1.10 # 1.9.x
  - DJANGO=django<1.11 # 1.10.x
  - DJANGO=django<1.12 # 1.11.x

# install dependencies
install:
  - pip install $DJANGO -r requirements-debug.txt

# run tests
script:
  - flake8 .
  - isort -c -df
  - PYTHONPATH=`pwd` py.test --cov-report html --cov=admin_view_permission -v tests/

# report coverage to coveralls.io
after_success: coveralls
