# Config file for automatic testing at travis-ci.org

language: python

# diferrent python versions
python:
  - "2.7"
  - "3.4"
  - "3.5"

# diferrent django versions
env:
  - DJANGO=1.9
  - DJANGO=1.8

# install dependencies
install:
  - pip install -r requirements-debug.txt
  - pip install Django==$DJANGO

# run tests
script:
  - PYTHONPATH=`pwd` py.test --cov-report html --cov=admin_view_permission -v tests/

# report coverage to coveralls.io
after_success: coveralls