# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

# command to install dependencies, e.g. pip install -r requirements.txt
#--use-mirrors
install: pip install -r requirements-debug.txt

# command to run tests
script: PYTHONPATH=`pwd` py.test --cov-report html --cov=admin_view_permission -v tests/

# report coverage to coveralls.io
after_success: coveralls