# Config file for automatic testing at travis-ci.org

language: python

cache: pip

# diferrent python versions
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# diferrent django versions
env:
  - DJANGO_VERSION=1.8.*
  - DJANGO_VERSION=1.9.*
  - DJANGO_VERSION=1.10.*
  - DJANGO_VERSION=1.11.*
  - DJANGO_VERSION=2.0.*

# install dependencies
install:
  - pip install -r requirements-debug.txt
  - pip install Django==$DJANGO_VERSION

# print pip packages
before_script:
  - pip freeze

# run tests
script:
  - flake8 .
  - isort -c -df
  - PYTHONPATH=`pwd` py.test --cov-report html --cov=admin_view_permission -v tests/

# report coverage to coveralls.io
after_success: coveralls
